import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-photo-view/dist/react-photo-view.css";

import { RadioButton } from "./components/ui/RadioButton";
import Providers from "./book/store/provrider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  icons: { icon: "/favicon.ico" },
  title: "Hamidreza-portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}     antialiased`}
      >
        <Providers>
          {" "}
          <RadioButton />
          <dialog id="dialog"></dialog>
          {children}
        </Providers>
      </body>
    </html>
  );
}
